// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_image_as_rgba`, `encode_jpeg_bytes`, `resize_rgba_image`, `validate_process_image_input`

/// Decodes image bytes, resizes to the target dimensions, and encodes as JPEG.
/// Async (non-`sync`) so flutter_rust_bridge runs it off the UI isolate.
Future<Uint8List> processImage(
        {required List<int> imageBytes,
        required int targetWidth,
        required int targetHeight,
        required int quality}) =>
    RustLib.instance.api.crateApiImageOpsProcessImage(
        imageBytes: imageBytes,
        targetWidth: targetWidth,
        targetHeight: targetHeight,
        quality: quality);
